"use client";

import { useState } from "react";
import { CheckCircle2, FilePlus2, FileSpreadsheet, Upload } from "lucide-react";
import { Button } from "@/components/ui/button";

type Mode = "manual" | "csv";
type Form = { title: string; organization: string; location: string; deadline: string; category: string; requirements: string };
const initialForm: Form = { title: "", organization: "", location: "", deadline: "", category: "建築一式・大規模改修", requirements: "" };

export default function ManualRegisterPage() {
  const [mode, setMode] = useState<Mode>("manual");
  const [form, setForm] = useState<Form>(initialForm);
  const [file, setFile] = useState<File | null>(null);
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");
  const [saving, setSaving] = useState(false);
  const update = (key: keyof Form, value: string) => setForm((current) => ({ ...current, [key]: value }));

  const submitManual = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); setMessage(""); setError(""); const response = await fetch("/api/bids", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, budgetMax: null }) }); const data = await response.json(); if (response.ok) { setMessage("案件をマスターへ登録しました。"); setForm(initialForm); } else setError(data.error ?? "登録に失敗しました。"); setSaving(false); };
  const submitCsv = async (event: React.FormEvent) => { event.preventDefault(); if (!file) return; setSaving(true); setMessage(""); setError(""); const body = new FormData(); body.append("file", file); const response = await fetch("/api/bids/import", { method: "POST", body }); const data = await response.json(); if (response.ok) { setMessage(`CSV登録が完了しました。新規${data.inserted}件、更新${data.updated}件。`); setFile(null); (event.currentTarget as HTMLFormElement).reset(); } else setError(data.error ?? "CSV登録に失敗しました。"); setSaving(false); };

  return <main className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-10"><div className="border-b border-slate-200 pb-6"><p className="text-xs font-bold tracking-[0.16em] text-indigo-600">MANUAL ENTRY</p><h1 className="mt-2 text-2xl font-bold tracking-tight">手動登録</h1><p className="mt-2 text-sm text-slate-600">収集元にない案件を、案件マスターへ登録します。</p></div>{message && <div className="mt-6 flex items-center gap-2 border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800"><CheckCircle2 className="h-4 w-4" />{message}</div>}{error && <div className="mt-6 border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800">{error}</div>}<div className="mt-6 flex border-b border-slate-200"><button type="button" onClick={() => setMode("manual")} className={`border-b-2 px-4 py-3 text-sm font-semibold ${mode === "manual" ? "border-indigo-600 text-indigo-700" : "border-transparent text-slate-500"}`}><FilePlus2 className="mr-2 inline h-4 w-4" />1件ずつ登録</button><button type="button" onClick={() => setMode("csv")} className={`border-b-2 px-4 py-3 text-sm font-semibold ${mode === "csv" ? "border-indigo-600 text-indigo-700" : "border-transparent text-slate-500"}`}><FileSpreadsheet className="mr-2 inline h-4 w-4" />CSV一括登録</button></div>{mode === "manual" ? <ManualForm form={form} update={update} submit={submitManual} saving={saving} /> : <form onSubmit={submitCsv} className="mt-6 max-w-3xl border border-slate-200 bg-white"><div className="border-b border-slate-200 px-5 py-4"><h2 className="text-sm font-bold">NJSS CSV一括登録</h2><p className="mt-1 text-xs text-slate-500">CSVの1行目を見出しとして読み込みます。最大5,000件。</p></div><div className="p-5"><label className="flex min-h-36 cursor-pointer flex-col items-center justify-center border border-dashed border-slate-300 bg-slate-50 px-5 text-center hover:border-indigo-400 hover:bg-indigo-50/30"><Upload className="h-6 w-6 text-slate-500" /><span className="mt-3 text-sm font-semibold text-slate-700">CSVファイルを選択</span><span className="mt-1 text-xs text-slate-500">案件名・発注機関が必須です</span><input type="file" accept=".csv,text/csv" onChange={(event) => setFile(event.target.files?.[0] ?? null)} className="sr-only" /></label>{file && <p className="mt-3 text-sm text-slate-700">選択中: <span className="font-semibold">{file.name}</span></p>}<div className="mt-5 border border-slate-200 bg-white p-4"><p className="text-xs font-semibold text-slate-700">対応する見出し</p><p className="mt-2 text-xs leading-5 text-slate-500">案件名、発注機関、地域、開札予定日、予定価格、工種、概要、詳細URL</p></div></div><div className="flex justify-end border-t border-slate-100 bg-slate-50 px-5 py-4"><Button type="submit" disabled={!file || saving}>{saving ? "登録中…" : "CSVを登録"}</Button></div></form>}</main>;
}

function ManualForm({ form, update, submit, saving }: { form: Form; update: (key: keyof Form, value: string) => void; submit: (event: React.FormEvent) => void; saving: boolean }) { return <form onSubmit={submit} className="mt-6 max-w-3xl border border-slate-200 bg-white"><div className="flex items-center gap-3 border-b border-slate-200 px-5 py-4"><FilePlus2 className="h-5 w-5 text-indigo-700" /><div><h2 className="text-sm font-bold">案件情報</h2><p className="mt-1 text-xs text-slate-500">* は必須項目です。</p></div></div><div className="grid gap-5 p-5 sm:grid-cols-2"><Field label="案件名 / 工事名称 *" value={form.title} onChange={(value) => update("title", value)} required className="sm:col-span-2" /><Field label="発注機関 *" value={form.organization} onChange={(value) => update("organization", value)} required /><Field label="対象地域" value={form.location} onChange={(value) => update("location", value)} /><Field label="開札予定日" type="date" value={form.deadline} onChange={(value) => update("deadline", value)} /><label className="block text-sm font-semibold text-slate-700">工種カテゴリ<select value={form.category} onChange={(event) => update("category", event.target.value)} className="mt-2 h-10 w-full border border-slate-300 bg-white px-3 text-sm font-normal outline-none focus:border-indigo-500 focus:ring-2 focus:ring-indigo-100"><option>建築一式・大規模改修</option><option>管工事・空調設備</option><option>電気設備工事</option><option>舗装工事・土木</option></select></label><label className="block text-sm font-semibold text-slate-700 sm:col-span-2">工事内容・参加資格要件<textarea rows={5} value={form.requirements} onChange={(event) => update("requirements", event.target.value)} className="mt-2 w-full border border-slate-300 px-3 py-2 text-sm font-normal outline-none focus:border-indigo-500 focus:ring-2 focus:ring-indigo-100" /></label></div><div className="flex justify-end border-t border-slate-100 bg-slate-50 px-5 py-4"><Button type="submit" disabled={saving}>{saving ? "登録中…" : "マスターへ登録"}</Button></div></form>; }
function Field({ label, value, onChange, type = "text", required, className = "" }: { label: string; value: string; onChange: (value: string) => void; type?: string; required?: boolean; className?: string }) { return <label className={`block text-sm font-semibold text-slate-700 ${className}`}>{label}<input required={required} type={type} value={value} onChange={(event) => onChange(event.target.value)} className="mt-2 h-10 w-full border border-slate-300 px-3 text-sm font-normal outline-none focus:border-indigo-500 focus:ring-2 focus:ring-indigo-100" /></label>; }
